version: "3.1"
services:
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: dockerfile
    ports:
      - 80:80
    volumes:
      - ./front:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
  back:
    container_name: back
    build:
      context: ./back
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
networks:
  default:
    name: tech-test
