FROM node:18.16-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn install --immutable

# add app
COPY . ./

EXPOSE 80
# start app
CMD ["yarn","dev"]
